server:
  port: 8080
  servlet:
    context-path: /SpringBootRestApi

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      # host: localhost
      # port: 27017
      # database: test
logging:
  file:
    name: logs/application.log
    append: true
  console:
    enabled: true
    pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} - %msg%n'
  level:
    com.springboot: DEBUG
    com.springboot.service.UserServiceImpl: TRACE